Request: Add WordPress plugin to description
Orange-OpenSource/Orange-Confort-plus pull request #286
Opened 2024-09-18 20:09 UTC by RavanH

For easy deployment on WordPress websites, the plugin https://wordpress.org/plugins/orange-confort-plus/ is available. It might be practical to add this fact to the Readme.

I've added a line with link to the WordPress.org plugin page as a suggestion :)

2024-10-18 08:42 UTC, ffoodd commented
@Lausselloic Should we merge this? I'm not sure about Orange's policies regarding such case.

2024-10-18 15:53 UTC, RavanH commented
Please let me know Orange stance on integration into a WordPress plugin. If not allowed, I'll retract the plugin immediately. If more/clearer accreditation is needed, I can make the plugin and its documentation compliant.

If a live use-case is needed to see how it is implemented, I can set up a WordPress development site with the plugin running.

2024-10-24 15:20 UTC, Lausselloic commented
Hello @RavanH,

First many thanks for your plugin, that would help users to easier integrate Confort+ with Wordpress. There's no reason to avoid it, it's opensource under GPLV2 and you're totally right to publish the source of your plugin.

We will add a mention and link to your plugin to the readme, but also indicate that this plugin is not "maintained" directly by the core team of this project to avoid confusion and ticket support onto the github repository if it's related to the plugin.

On your side, if you could **add the version of Orange Confort+** embeded inside your plugin onto the description page could be usefull for endusers. As the team is working on a new version (And we wonder you could update your plugin when it will be available)

And just a latest reminder that you're not allowed to use Orange Brand elements (like logo) as they were the property of the company and not of the opensource project.

2024-10-24 15:30 UTC, Lausselloic commented
I've update the wording inside the readme, let me know if you agree with it, and if you've a link for dedicated support onto the plugin where I could link to.

2024-10-25 07:22 UTC, Lausselloic commented
> Hi @Lausselloic
> 
> > We will add a mention and link to your plugin to the readme, but also indicate that this plugin is not "maintained" directly by the core team of this project to avoid confusion and ticket support onto the github repository if it's related to the plugin.
> 
> A good idea!
> 
> > On your side, if you could **add the version of Orange Confort+** embeded inside your plugin onto the description page could be usefull for endusers. As the team is working on a new version (And we wonder you could update your plugin when it will be available)
> 
> Will do that :)
> 
> > And just a latest reminder that you're not allowed to use Orange Brand elements (like logo) as they were the property of the company and not of the opensource project.
> 
> I've not included any Orange brand elements. As alternative, I've opted to simply use an orange plus sign. But I did include images from the Confort + documentation on https://confort-plus.orange.com/index_en.html. You can see these under "Captures d’écran" on https://fr.wordpress.org/plugins/orange-confort-plus/ ...
> 
> Please let me know if this is not acceptable :)

Yes everything is fine at time, all image of Orange Confort+ himself is okay.

2024-10-25 14:05 UTC, notabene requested changes

2024-10-25 14:05 UTC, notabene commented on README.md
> +You could use the plugin [Orange Confort+ for WordPress](https://wordpress.org/plugins/orange-confort-plus/) is available. Thanks to [@RavanH](https://github.com/RavanH).
→ A tailor-made [Orange Confort+ for WordPress](https://wordpress.org/plugins/orange-confort-plus/) plugin is available.

2024-10-25 14:50 UTC, merged

2024-10-25 15:07 UTC, RavanH commented
Thanks @all :)

One quick question about the upcoming version 5.0.0 : is there an option  to host the dist/serveur/ files in a subdirectory like the `hebergementFullPath` in v4 ? I'm not seeing any possibilities in alpha7 where any path variables seem to default to `window.location.origin` ...

2024-10-25 20:31 UTC, ffoodd commented
No indeed, that's something that'll need to be added.